### ISSUE TITLE
sequence_diagram.txt

### ISSUE THREAD

**Issue by jakeflynn56** [apeled/TLDhubeR#13]
[https://github.com/apeled/TLDhubeR/blob/docs/docs/sequence_diagram.txt](url)

@edouas : For the last few steps here, doesn't the OpenAI API feed directly to the Streamlit App once the context is added to the GPT model? I could be wrong on this, but I just wanted to verify.

**Comment by edouas** [comment]
Good point Jake. Made the change 👍
